dataset:
  #folder: "../sim_data" # folder to save data
  folder: "/media/motion/Elements/adaptigraph/sim_data"
  obj: "softbody"
  save_dir: "epi-20-damping-2-flatboard-softbody-cubes-deeper-forward-poke-s-m-e-e-waypoints"
  #save_dir: "softbody-poking-s-m-e-e-waypoints"

  # data collection
  base: 0 #37
  n_episode: 20 #1000
  n_timestep: 5
  n_worker: 2
  
  # sim env
  headless: True # False: OpenGL visualization
  camera_view: 1 # 0 (top view), 1, 2, 3, 4
  screenWidth: 720
  screenHeight: 720

  robot_type: 'xarm6' 
  robot_end_idx: 6
  robot_num_dofs: 6
  robot_speed_inv: 300 #300
  #robot_num_dofs: 12
  #robot_speed_inv: 100
  
  action_dim: 6 # now needs to include y_start, y_end. Prev: 4 [x_start, z_start, x_end, z_end]
  action_space: 6 # 4 random action space scope
  action_type: "poke"

  # Tool
  # For the stick pusher
  #gripper: False
  #pusher_len: 1.0
  # For the gripper
  #gripper: True
  #pusher_len: 1.8
  # For the flatboard pusher
  gripper: False
  pusher_len: 1.3
  
  # Save particles
  fps: False
  fps_number: 2000

  rob_obj_dist_thresh: 0.2
  contact_interval: 40
  non_contact_interval: 80
  #contact_interval: 10
  #non_contact_interval: 30

  # others
  color_threshold: 0.0001