dataset_config:
  data_name: "multiobj"
  output_name: "sphere-3multiobj-far-apart-homo-connect-all-false-softbody"
  materials: ["multiobj"]
  data_dir: "../sim_data" # data directory
  prep_data_dir: "../preprocess" # preprocessed data directory
  device: "cuda:0"

  verbose: False
  # preprocess
  n_his: 4
  n_future: 3
  dist_thresh: 0.1 # 1.0cm

  ratio:
    train: [0, 0.98]
    valid: [0.98, 1]

  eef:
    #max_neef: 1
    #name: ['stick_pusher']
    #pos: [[0., 0., 1.]]
    max_neef: 2
    name: ['left_finger', 'right_finger']
    pos: [[0., -0.2, 0.6],
          [0., 0.2, 0.6]]
  
  datasets:
    - name: 'multiobj'
      max_nobj: 100
      max_nR: 1000
      #fps_radius_range: [0.18, 0.22]
      #adj_radius_range: [0.48, 0.52]
      #opk: 10
      connect_tool_all: False
      fps_radius_range: [0.24, 0.26]
      adj_radius_range: [0.74, 0.76]
      topk: 5
      #connect_tool_all: True
  
  randomness: 
    use: False
    state_noise:
      train: 0.05
      valid: 0.0
    phys_noise:
      train: 0.0
      valid: 0.0
    
train_config:
  out_dir: "../log"
  phases: ['train', 'valid']
  num_workers: 8
  random_seed: 42
  verbose: False

  batch_size: 128
  n_epochs: 100
  n_iters_per_epoch: 
    train: 1000
    valid: 100
  log_interval: 50

model_config:
  verbose: False

  nf_particle: 150
  nf_relation: 150
  nf_effect: 150
  nf_physics: 10

  # particle encoder
  attr_dim: 2 # object and eef
  state_dim: 0 # x, y, z 
  offset_dim: 0
  action_dim: 3
  density_dim: 0 # particle density

  pstep: 3 # propagation steps
  sequence_len: 4
  
  # relation encoder
  rel_particle_dim: 0
  rel_attr_dim: 2 # within objects, object-eef
  rel_group_dim: 1 # sum of difference of group one-hot vector
  rel_distance_dim: 3
  rel_density_dim: 0

rollout_config:
  out_dir: "../rollout"
  rollout_steps: 100

material_config:
  material_index:
    multiobj: 0
  multiobj:
    physics_params: 
      - name: "particle_radius"
        use: False
        min: 0.
        max: 1.
      - name: "num_particles"
        use: False
        min: 0.
        max: 5000.
      - name: "cluster_radius"
        use: False
        min: 0.
        max: 15.0
      - name: "cluster_spacing"
        use: False
        min: 0.
        max: 20.0
      - name: "dynamic_friction"
        use: False
        min: 0.1
        max: 0.45
      - name: "stiffness"
        use: True
        min: 0.
        max: 1.
