dataset_config:
  data_name: "softbody"
  #data_folder: "epi-100-xz-scale-10-13-y-scale-10-18-vary-og-global-stiff-cluster-spacing-softbody-cubes-flatboard-poke-and-retreat-center-dist-thres-0-1"
  #output_name: "y-trans-x-rot-90-flatboard-softbody-cylinder-damping-2-deep-poke-then-lift-s-m-e-e-m-s-waypoints"
  #output_name: "max-nR-3500-pstep-4-nhis-5-store-rest-state-epi-100-xz-scale-10-13-y-scale-10-18-vary-og-global-stiff-cluster-spacing-softbody-cubes-flatboard-poke-and-retreat-center-dist-thres-0-1"
  #data_folder: "epi-100-damping-2-flatboard-softbody-cubes-deeper-poke-and-lift-s-m-e-e-m-s-waypoints"
  #data_folder: "epi-20-xz-scale-10-13-y-scale-10-18-vary-og-global-stiff-cluster-spacing-softbody-cubes-flatboard-poke-and-retreat-center-dist-thres-0-1"
  #data_folder: "epi-10-xz-scale-10-13-y-scale-10-18-og-stiff-0-5-to-1-softbody-cubes-flatboard-poke-and-retreat-center-dist-thres-0-1"
  #data_folder: "epi-5-smaller-actual-similar-size-softbody-cubes-flatboard-deeper-poke-and-lift"
  #output_name: "max-nobj-300-connect-tool-all-non-fixed-pstep-4-train-epi-100-xz-scale-10-13-y-scale-10-18-vary-og-global-stiff-cluster-spacing-softbody-cubes-flatboard-poke-and-retreat-center-dist-thres-0-1"
  #output_name: "include-rest-state-kNN-tool-to-object-train-epi-100-xz-scale-10-13-y-scale-10-18-vary-og-global-stiff-cluster-spacing-softbody-cubes-flatboard-poke-and-retreat-center-dist-thres-0-1"
  #data_folder: "mini-test-set-base-101-for-epi-100-xz-scale-10-13-y-scale-10-18-vary-og-global-stiff-cluster-spacing-softbody-cubes-flatboard-poke-and-retreat-center-dist-thres-0-1"
  #output_name: "testing-pure-soft-volumetric-elastic-rollout-train-14-16-epi-100-xz-scale-10-13-y-scale-10-18"
  #data_folder: "epi-1006-xz-scale-10-13-y-scale-10-18-vary-og-global-stiff-cluster-spacing-softbody-cubes-flatboard-poke-and-retreat-center-dist-thres-0-1"
  #output_name: "include-rest-state-kNN-tool-to-object-val-epi-1006-xz-scale-10-13-y-scale-10-18-vary-og-global-stiff-cluster-spacing-softbody-cubes-flatboard-poke-and-retreat-center-dist-thres-0-1"
  # data_folder: "rigid-mesh-mixed-test-radius-0-05"
  # output_name: "rigid-mesh-mixed-test-radius-0-05"
  data_folder: "softbody_with_different_cluster_spacing_per_cluster"
  output_name: "softbody_with_different_cluster_spacing_per_cluster"
  materials: ["softbody"]
  #data_dir: "../sim_data" # data directory
  data_dir: "/media/motion/Elements/adaptigraph/sim_data"
  #prep_data_dir: "../preprocess" # preprocessed data directory
  prep_data_dir: "/media/motion/Elements/adaptigraph/preprocess"
  device: "cuda:0"

  verbose: False
  # preprocess
  n_his: 5 #4 To include the rest state in history, +1
  n_future: 3
  dist_thresh: 0.1 # 1.0cm

  # history kps
  store_rest_state: True

  ratio:
    #train: [0, 0.9]
    #valid: [0.9, 1]
    #train: [0, 0.98]
    #valid: [0.98, 1]
    train: [0, 0]
    valid: [0, 1]
    #train: [0, 0]
    #valid: [0.14, 0.17]

  eef:
    #max_neef: 1
    #name: ['stick_pusher']
    #pos: [[0., 0., 1.]]
    #max_neef: 2
    #name: ['left_finger', 'right_finger']
    #pos: [[0., -0.2, 0.6],
    #      [0., 0.2, 0.6]]
    # For flatboard pusher
    max_neef: 5 # TODO: increase to better represent shape of flatboard
    name: ['flat_pusher']
    pos: [[0.5, 0.045, 1.25],
          [-0.5, 0.045, 1.25],
          [0., 0.045, 1.25],
          [0.25, 0.045, 1.25],
          [-0.25, 0., 1.25]]
  
  datasets:
    - name: 'softbody'
      max_nobj: 300 #300
      max_nR: 3500 #1000
      #fps_radius_range: [0.18, 0.22]
      fps_radius_range: [0.20, 0.24]
      adj_radius_range: [0.48, 0.52]
      topk: 10
      #connect_tool_all: False
      #fps_radius_range: [0.24, 0.26]
      #adj_radius_range: [0.74, 0.76]
      #topk: 5
      #connect_tool_all: False
      # For granular
      #fps_radius_range: [0.18, 0.22]
      #adj_radius_range: [0.38, 0.42]
      #topk: 20
      connect_tool_all: False
      connect_tool_surface: False
      connect_tool_surface_ratio: 1.0
      connect_tool_all_non_fixed: True # Set this flag to true to connect to the tool to the closest particles
      knn_range: [0.4, 1.0]
      min_knn: 0.4
      knn_increment: 0.1
  
  randomness: 
    use: False
    state_noise:
      train: 0.05
      valid: 0.0
    phys_noise:
      train: 0.0
      valid: 0.0
    
train_config:
  out_dir: "../log"
  phases: ['train', 'valid']
  num_workers: 0 #8
  random_seed: 42
  verbose: True

  batch_size: 128
  n_epochs: 100
  n_iters_per_epoch: 
    train: 1000
    valid: 100
  log_interval: 50

model_config:
  verbose: True

  nf_particle: 150
  nf_relation: 150
  nf_effect: 150
  nf_physics: 10

  # particle encoder
  attr_dim: 2 # object and eef
  state_dim: 0 # x, y, z 
  offset_dim: 0
  action_dim: 3 # action from construct graph is states_delta: (N_obj + N_eef, 3)
  density_dim: 0 # particle density

  pstep: 4 # propagation steps
  sequence_len: 4
  
  # relation encoder
  rel_particle_dim: 0
  rel_attr_dim: 2 # within objects, object-eef
  rel_group_dim: 1 # sum of difference of group one-hot vector
  rel_distance_dim: 3
  rel_density_dim: 0

rollout_config:
  #out_dir: "../rollout"
  out_dir: "/media/motion/Elements/adaptigraph/rollout"
  rollout_steps: 100

material_config:
  material_index:
    softbody: 0
  softbody:
    physics_params: 
      - name: "particle_radius"
        use: False
        min: 0.
        max: 1.
      - name: "num_particles"
        use: False
        min: 0.
        max: 5000.
      - name: "cluster_radius"
        use: False
        min: 0.
        max: 15.0
      - name: "cluster_spacing"
        use: False
        min: 0.
        max: 20.0
      - name: "dynamic_friction"
        use: False
        min: 0.1
        max: 0.45
      - name: "stiffness"
        use: True
        min: 0.
        max: 1.
